"""
Autonomous Competitive Intelligence Agent - Pydantic Schemas

Defines typed message contracts for multi-agent fan-out execution,
specialist domain reports, conflict adjudication, and final intelligence briefings.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime
from pydantic import BaseModel, Field, field_validator


class SubQuestion(BaseModel):
    """Sub-question generated by Orchestrator Agent."""
    category: str = Field(..., description="Domain category (market, product, tech, news, sentiment)")
    question: str = Field(..., description="Target research question")
    assigned_agent: str = Field(..., description="Target specialist agent name")


class ResearchPlan(BaseModel):
    """Research strategy produced by Orchestrator Agent."""
    company_name: str = Field(..., description="Target company name")
    sub_questions: List[SubQuestion] = Field(..., description="List of sub-questions for parallel fan-out")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())


class MarketReport(BaseModel):
    """Market position and sizing analysis produced by Market Agent."""
    market_share_estimate: str = Field(..., description="Estimated market share")
    tam_sam_som: str = Field(..., description="Total Addressable Market metrics")
    growth_rate: str = Field(..., description="Annual growth rate estimate")
    key_competitors: List[str] = Field(..., description="Primary direct competitors")
    confidence: float = Field(..., description="Agent confidence score (0.0 - 1.0)")

    @field_validator('confidence')
    @classmethod
    def validate_conf(cls, v: float) -> float:
        return max(0.0, min(1.0, v))


class ProductReport(BaseModel):
    """Product features and differentiators produced by Product Agent."""
    core_offerings: List[str] = Field(..., description="Main products or services")
    key_differentiators: List[str] = Field(..., description="Unique selling propositions")
    pricing_model: str = Field(..., description="Pricing structure details")
    feature_gaps: List[str] = Field(..., description="Identified product limitations or gaps")
    confidence: float = Field(..., description="Agent confidence score (0.0 - 1.0)")

    @field_validator('confidence')
    @classmethod
    def validate_conf(cls, v: float) -> float:
        return max(0.0, min(1.0, v))


class TechStackReport(BaseModel):
    """Inferred architecture and tech stack choices by Tech Stack Agent."""
    frontend_tech: List[str] = Field(..., description="Frontend frameworks and tools")
    backend_tech: List[str] = Field(..., description="Backend languages and frameworks")
    cloud_infra: List[str] = Field(..., description="Cloud infrastructure and databases")
    ai_ml_stack: List[str] = Field(..., description="AI/ML models and orchestration frameworks")
    confidence: float = Field(..., description="Agent confidence score (0.0 - 1.0)")

    @field_validator('confidence')
    @classmethod
    def validate_conf(cls, v: float) -> float:
        return max(0.0, min(1.0, v))


class NewsReport(BaseModel):
    """Recent news and regulatory events produced by News Agent."""
    recent_funding: str = Field(..., description="Recent funding rounds or financial status")
    major_announcements: List[str] = Field(..., description="Recent press releases and product launches")
    regulatory_impacts: List[str] = Field(..., description="Legal, compliance, or regulatory developments")
    confidence: float = Field(..., description="Agent confidence score (0.0 - 1.0)")

    @field_validator('confidence')
    @classmethod
    def validate_conf(cls, v: float) -> float:
        return max(0.0, min(1.0, v))


class SentimentReport(BaseModel):
    """Customer and analyst sentiment produced by Sentiment Agent."""
    overall_sentiment: str = Field(..., description="Overall market sentiment rating")
    customer_satisfaction_score: float = Field(..., description="CSAT / NPS score estimate (0 - 100)")
    analyst_rating: str = Field(..., description="Analyst stance (e.g. Bullish, Neutral, Bearish)")
    key_praises: List[str] = Field(..., description="Top customer praise points")
    key_complaints: List[str] = Field(..., description="Top customer complaints")
    confidence: float = Field(..., description="Agent confidence score (0.0 - 1.0)")

    @field_validator('confidence')
    @classmethod
    def validate_conf(cls, v: float) -> float:
        return max(0.0, min(1.0, v))


class ConflictItem(BaseModel):
    """Contradiction flagged and adjudicated by Conflict Resolver."""
    topic: str = Field(..., description="Topic of contradiction")
    agent_a: str = Field(..., description="First agent name")
    claim_a: str = Field(..., description="Claim from first agent")
    agent_b: str = Field(..., description="Second agent name")
    claim_b: str = Field(..., description="Claim from second agent")
    resolution: str = Field(..., description="Adjudicated verdict and reasoning")
    verdict_agent: str = Field(..., description="Favored agent or synthesized middle ground")


class CompetitiveBriefing(BaseModel):
    """Structured final intelligence briefing output."""
    company_name: str = Field(..., description="Target company analyzed")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    executive_summary: str = Field(..., description="High-level executive briefing")
    market_analysis: MarketReport = Field(..., description="Market sizing report")
    product_analysis: ProductReport = Field(..., description="Product analysis report")
    tech_stack_analysis: TechStackReport = Field(..., description="Tech stack report")
    recent_news: NewsReport = Field(..., description="News developments report")
    sentiment_analysis: SentimentReport = Field(..., description="Sentiment report")
    conflicts_resolved: List[ConflictItem] = Field(default_factory=list, description="Resolved agent contradictions")
    strategic_recommendations: List[str] = Field(..., description="Actionable recommendations")
    total_tokens: int = Field(default=0, description="Total tokens consumed across all agents")
    execution_time_sec: float = Field(default=0.0, description="Total execution time in seconds")
    cost_usd: float = Field(default=0.0, description="Estimated total API cost USD")
